version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
    goos:
      - linux
      - darwin
    goarm:
      - "6"
      - "7"
    ldflags:
      - -s -w
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile.release
    image_templates:
      - "systemli/userli-webhook-listener:{{ .Tag }}"
      - "systemli/userli-webhook-listener:{{ .Major }}"
      - "systemli/userli-webhook-listener:{{ .Major }}.{{ .Minor }}"
      - "systemli/userli-webhook-listener:latest"
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  disable: true
